import { Area, AreaChart, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CircleDollarSign, TrendingDown } from 'lucide-react'

const spending = [{ name: 'Hotel', value: 4000 }, { name: 'Food', value: 2500 }, { name: 'Travel', value: 2000 }, { name: 'Shopping', value: 1500 }]
const trend = [{ day: 'Mon', spend: 820 }, { day: 'Tue', spend: 1240 }, { day: 'Wed', spend: 1680 }, { day: 'Thu', spend: 2210 }, { day: 'Fri', spend: 2860 }, { day: 'Sat', spend: 3600 }, { day: 'Sun', spend: 10000 }]
const colors = ['#e9785f', '#20a39e', '#3b6ea5', '#f1b24a']

export default function Budget() {
  return <><div className="page-heading"><div><p className="eyebrow">Make every rupee count</p><h1>Budget dashboard</h1><p className="page-subtitle">A clear picture of your ₹10,000 Jaipur trip budget.</p></div></div><div className="stats-grid"><article className="stat-card"><div className="stat-top"><span>Total planned</span><CircleDollarSign size={17} className="stat-icon" /></div><div className="stat-value">₹10,000</div><div className="stat-note">Across 4 categories</div></article><article className="stat-card"><div className="stat-top"><span>Daily average</span><TrendingDown size={17} className="stat-icon" /></div><div className="stat-value">₹3,333</div><div className="stat-note">3 day itinerary</div></article></div><div className="chart-grid"><section className="panel chart-panel"><div className="panel-header"><h2>Spend by category</h2><span className="panel-link">Donut</span></div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={spending} dataKey="value" nameKey="name" innerRadius={70} outerRadius={100} paddingAngle={4}>{spending.map((entry, index) => <Cell key={entry.name} fill={colors[index]} />)}</Pie><Tooltip formatter={(value) => `₹${value}`} /><Legend /></PieChart></ResponsiveContainer></section><section className="panel chart-panel"><div className="panel-header"><h2>Category split</h2><span className="panel-link">Pie</span></div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={spending} dataKey="value" nameKey="name" outerRadius={100}>{spending.map((entry, index) => <Cell key={entry.name} fill={colors[index]} />)}</Pie><Tooltip formatter={(value) => `₹${value}`} /><Legend /></PieChart></ResponsiveContainer></section></div><section className="panel chart-panel"><div className="panel-header"><h2>Budget burn rate</h2><span className="panel-link">Day vs spend</span></div><ResponsiveContainer width="100%" height={260}><AreaChart data={trend}><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip formatter={(value) => `₹${value}`} /><Area type="monotone" dataKey="spend" stroke="#20a39e" fill="#bfe8e3" strokeWidth={3} /></AreaChart></ResponsiveContainer></section></>
}
