import { Ambulance, ExternalLink, LoaderCircle, Phone, ShieldAlert, Siren } from 'lucide-react'
import { useState } from 'react'
import api from '../services/api'

export default function Emergency() {
	const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
	const triggerSos = () => { setLoading(true); setError(''); if (!navigator.geolocation) { setError('This browser does not support location services.'); setLoading(false); return } navigator.geolocation.getCurrentPosition(async ({ coords }) => { try { const response = await api.post('/api/sos', { latitude: coords.latitude, longitude: coords.longitude }); setResult(response.data) } catch { setError('Emergency service is unavailable. Call local emergency services directly.') } finally { setLoading(false) } }, () => { setError('Location permission is required to find nearby help.'); setLoading(false) }, { enableHighAccuracy: true, timeout: 10000 }) }
	return <><div className="page-heading"><div><p className="eyebrow">Stay ready</p><h1>Emergency hub</h1><p className="page-subtitle">One tap to share your location and find the nearest help.</p></div><button className="sos-button" type="button" onClick={triggerSos} disabled={loading}>{loading ? <LoaderCircle className="spin" size={20} /> : <Siren size={20} />}{loading ? 'Locating...' : 'SOS'}</button></div>{error && <p className="form-error">{error}</p>}{result && <section className="sos-result"><div><p className="eyebrow">Location shared</p><h2>Help is mapped nearby</h2><p>Services are sorted by distance from your current position.</p></div><a className="primary-button" href={result.route_url} target="_blank" rel="noreferrer">Open route <ExternalLink size={15} /></a><div className="service-results">{result.services.map((service) => <div className="service-result" key={service.type}><strong>{service.name}</strong><span>{service.type === 'hospital' ? 'Hospital' : 'Police station'} · {service.distance_km} km</span><a href={`tel:${service.phone}`}>Call {service.phone}</a></div>)}</div></section>}<section className="panel"><div className="panel-header"><h2>Local emergency contacts</h2><span className="status">Jaipur, IN</span></div><div className="table-list">{[[Ambulance,'Medical emergency','112','24 / 7'],[ShieldAlert,'Police','112','24 / 7'],[Phone,'Embassy support','+91 11 2419 8000','Open now']].map(([Icon, label, number, availability]) => <div className="table-line" key={label}><strong><Icon size={15} /> {label}</strong><span>{number}</span><strong>{availability}</strong></div>)}</div></section></>
}
