import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet'
import { MapPinned } from 'lucide-react'
import 'leaflet/dist/leaflet.css'
import { useState } from 'react'

const points = { Attractions: [{ name: 'Hawa Mahal', position: [26.9239, 75.8267], cost: '₹200', rating: '4.5', distance: '1.2 km' }, { name: 'City Palace', position: [26.9258, 75.8237], cost: '₹300', rating: '4.6', distance: '1.8 km' }], Hotels: [{ name: 'Rambagh Palace', position: [26.8915, 75.8067], cost: '₹18,000/night', rating: '4.8', distance: '4.6 km' }], Hospitals: [{ name: 'Sawai Man Singh Hospital', position: [26.9005, 75.8056], cost: 'Emergency 24/7', rating: '4.1', distance: '3.8 km' }], 'Police Stations': [{ name: 'Ashok Nagar Police Station', position: [26.9092, 75.7956], cost: 'Emergency 24/7', rating: '4.0', distance: '2.9 km' }] }
const colors = { Attractions: '#e9785f', Hotels: '#20a39e', Hospitals: '#d64b61', 'Police Stations': '#3b6ea5' }

export default function Maps() {
	const [visible, setVisible] = useState(Object.keys(points).reduce((all, key) => ({ ...all, [key]: true }), {}))
	return <><div className="page-heading"><div><p className="eyebrow">Know your surroundings</p><h1>Maps</h1><p className="page-subtitle">Explore Jaipur essentials with live location context.</p></div></div><section className="panel map-panel"><div className="map-toolbar">{Object.keys(points).map((layer) => <label className="layer-toggle" key={layer}><input type="checkbox" checked={visible[layer]} onChange={() => setVisible({ ...visible, [layer]: !visible[layer] })} /><i style={{ background: colors[layer] }} />{layer}</label>)}</div><MapContainer center={[26.9124, 75.7873]} zoom={13} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{Object.entries(points).flatMap(([layer, locations]) => visible[layer] ? locations.map((place) => <CircleMarker key={place.name} center={place.position} radius={9} pathOptions={{ color: colors[layer], fillColor: colors[layer], fillOpacity: .85 }}><Popup><strong>{place.name}</strong><br />Cost: {place.cost}<br />Rating: {place.rating}<br />Distance: {place.distance}</Popup></CircleMarker>) : [])}</MapContainer><div className="map-caption"><MapPinned size={16} /> Click an attraction or service marker for cost, rating, and distance.</div></section></>
}
